### ISSUE TITLE
Several icons not show in Firefox

### ISSUE THREAD

**Issue by azakus** [PolymerElements/iron-icons#32] opened 2015-11-06 19:22 UTC
_From @shawnsz on October 30, 2015 16:14_

Hi,

I'm using Polymer in my website. It's cool. But I found some icons not working in Firefox. Please take a look:
https://elements.polymer-project.org/elements/iron-icons?view=demo:demo/index.html

Several icons not show in Firefox. 
browser version: 41.0.2
OS: Windows 7 Professional Service Pack 1.

works fine in Chrome and IE 11

icons:flight-takeoff
icons:event-seat
icons:gif
icons:indeterminate-check-box

Thanks!
Shawn

_Copied from original issue: Polymer/polymer#2651_

**Comment by notwaldorf** [comment] 2015-12-16 01:24
Duplicate of https://github.com/PolymerElements/iron-icons/issues/28

**Closed by notwaldorf** 2015-12-16 01:24 UTC
